## Q1

In [2]:
import numpy as np

In [22]:
arr1=np.arange(2,14).reshape(4,3)
arr1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

## Q2

In [25]:
arr1=np.random.randint(1,50,20)
arr1[arr1%2 != 0] = -1
arr1

array([-1, 36, -1, -1, -1,  8, -1, -1, 30, 16, -1, 12, 22, -1,  2, -1, 36,
       -1, -1, 42])

## Q3

In [3]:
p=np.array([6999,7500,11999,27899,14999,9999])
p

array([ 6999,  7500, 11999, 27899, 14999,  9999])

In [24]:
p.astype(float)

array([ 6999.,  7500.,  9999., 11999., 14999., 27899.])

In [25]:
p=np.append(p,13999)
p

array([ 6999,  7500,  9999, 11999, 14999, 27899, 13999])

In [26]:
p[::-1]

array([13999, 27899, 14999, 11999,  9999,  7500,  6999])

In [30]:
gst=p*1.18
gst

array([ 8258.82,  8850.  , 11798.82, 14158.82, 17698.82, 32920.82,
       16518.82])

In [31]:
np.sort(gst)[::-1]

array([32920.82, 17698.82, 16518.82, 14158.82, 11798.82,  8850.  ,
        8258.82])

In [36]:
gst.mean()

15743.560000000001

In [35]:
gst.min()

8258.82

In [34]:
gst.max()

32920.82

In [33]:
gst.max() - gst.min()

24662.0

## Q4

In [33]:
a=np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)