In [1]:
import numpy as np
import pandas as pd

## Q1

In [3]:
arr1=np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Q2

In [4]:
arr1=np.array([10,20,30,40,50])
arr1

array([10, 20, 30, 40, 50])

# Q3

In [11]:
arr1=np.arange(0,9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Q4

In [15]:
arr1.shape


(3, 3)

In [16]:
arr1.size

9

In [17]:
arr2=np.random.randint(1,101,(5,4))
arr2

array([[35, 85, 79, 47],
       [84,  8, 88, 34],
       [ 8, 86, 51, 46],
       [52, 33,  2, 34],
       [52, 70,  1, 29]])

In [18]:
arr2.shape

(5, 4)

In [19]:
arr2.size

20

# Q5

In [2]:
arr1=np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
arr1[0,1]

1

In [4]:
arr1[1,2]

5

In [7]:
arr1[:2,1:]

array([[1, 2],
       [4, 5]])

# Q6

In [8]:
arr1=np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
arr1.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Q7

In [10]:
arr1=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr1.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Q8

In [27]:
arr1=np.arange(6).reshape(2,3)
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
arr2=np.arange(2,8).reshape(2,3)
arr2

array([[2, 3, 4],
       [5, 6, 7]])

In [32]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [33]:
arr2-arr1

array([[2, 2, 2],
       [2, 2, 2]])

In [34]:
arr1-arr2

array([[-2, -2, -2],
       [-2, -2, -2]])

In [35]:
arr1*arr2

array([[ 0,  3,  8],
       [15, 24, 35]])

In [36]:
arr1/arr2

array([[0.        , 0.33333333, 0.5       ],
       [0.6       , 0.66666667, 0.71428571]])

# Q9

In [38]:
arr1=np.arange(8)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [40]:
arr1.sum()

28

In [41]:
arr1.mean()

3.5

In [42]:
arr1.std()

2.29128784747792

# Q10

In [46]:
A=np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [45]:
B=np.arange(4).reshape(2,2)
B

array([[0, 1],
       [2, 3]])

In [49]:
A @ B

array([[ 2,  3],
       [ 6, 11]])

In [51]:
C=np.dot(A,B)
C

array([[ 2,  3],
       [ 6, 11]])

# Q11

In [52]:
A.T

array([[0, 2],
       [1, 3]])

In [53]:
B.T

array([[0, 2],
       [1, 3]])

# Q12

In [54]:
arr1=np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
arr2=np.arange(3)
arr2

array([0, 1, 2])

In [56]:
arr1+arr2

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

# Q13

In [57]:
arr1=np.random.randint(1,50,16).reshape(4,4)
arr1

array([[16, 31, 36, 16],
       [35, 43, 45, 28],
       [18, 47, 13, 26],
       [33,  7, 25,  4]])

In [59]:
arr1.min()

4

In [60]:
arr1.max()

47

In [61]:
arr1.mean()

26.4375

# Q14

In [74]:
arr1=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])


In [75]:
arr1.sum(axis=1)

array([ 6, 15, 24])

In [76]:
arr1.sum(axis=0)

array([12, 15, 18])

# Q15

In [62]:
arr1=np.random.randint(1,50,10)
arr1

array([34, 46, 41, 49, 19, 19, 12, 40, 12,  7])

# Q16

In [71]:
arr1=np.random.rand(25).reshape(5,5)
arr1

array([[0.90937945, 0.73237476, 0.77436038, 0.41219535, 0.99752772],
       [0.76745228, 0.17515398, 0.25029748, 0.70617021, 0.7358392 ],
       [0.5426138 , 0.60508464, 0.98033802, 0.8134177 , 0.40513714],
       [0.92020924, 0.73145496, 0.64776404, 0.5587874 , 0.73480467],
       [0.31148209, 0.51079094, 0.68159446, 0.81762535, 0.32983077]])